package me.voxelsquid.ignis.humanoid.personality

enum class PersonalityType {
    DEPRESSED, OPTIMISTIC, PESSIMISTIC, KIND, RUDE, MEAN, EMOTIONAL, CYNICAL, COLD, FORMAL,
    FRIENDLY, FAMILIAR, HUMOROUS, TALKATIVE, IRONIC, SARCASTIC, SERIOUS, NOSTALGIC, WITTY,
    ADVENTUROUS, MYSTERIOUS, DREAMY, IMPULSIVE, OBSESSIVE, RECKLESS, HUMBLE, FORGIVING,
    RATIONAL, ARTISTIC, ANXIOUS, PLAYFUL, RELAXED, GRUMPY, INTELLECTUAL, NAIVE, IGNORANT,
    ANGRY, MAD_SCIENTIST, DRUNKARD, SANE, ROMANTIC, REBELLIOUS, DRAMATIC, LUCKY, UNLUCKY,
    THIEF, POTHEAD, RANDOM, EVIL, SHAMAN, PHILOSOPHICAL
}